### ISSUE TITLE
There is an error,please add a @NgModule annotation.

### ISSUE THREAD

**Issue by ychost** [joaogarin/angular2-electron#75] opened 2017-05-22 13:40 UTC
Uncaught Error: Unexpected directive 'MdSlideToggle' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by ddamko** [comment] 2017-05-25 21:05
Same here and it looks like it is related to AOT with Angular 4. See the issue raised here: https://github.com/angular/angular-cli/issues/6429

And the solution was linked to here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/linked-library.md

**Comment by joaogarin** [comment] 2017-06-06 19:55
Hello,

So, Sorry this was my bad. But was actually a simple one. The problem is I was importing the 

```MdSlideToggle``` (directive) 

as if it was a module, but what should be imported is :  

```MdSlideToggleModule```

The fix is here : https://github.com/joaogarin/angular-electron/commit/58c90ab9a4b3df44423ea9fed96e977b722a0dfc

Thanks for the feedback I will close it now;)

**Closed as completed** 2017-06-06 19:55 UTC
